# Generated by Django 5.2 on 2026-01-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretleveldata',
            options={'permissions': [('view_secret_level_data', 'Can view secret level data.')], 'verbose_name_plural': 'Secret Level Data'},
        ),
        migrations.AlterModelOptions(
            name='topsecretleveldata',
            options={'permissions': [('view_top_secret_level_data', 'Can view top secret level data.')], 'verbose_name_plural': 'Top Secret Level Data'},
        ),
    ]
