# Generated by Django 6.0.1 on 2026-01-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_data', '0002_alter_secretleveldata_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopSecretLevelData',
        ),
    ]
