# Generated by Django 6.0.1 on 2026-01-20 23:46

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_date_completed_task_user_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', encrypted_model_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
