# Generated by Django 6.0.1 on 2026-01-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_completedtasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedTasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_completed',
        ),
    ]
