# Generated by Django 6.0.1 on 2026-01-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_date_completed_task_user_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_completed',
        ),
    ]
