# Generated by Django 6.0.1 on 2026-01-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_completed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
