# Generated by Django 6.0.1 on 2026-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_user_completed'),
    ]

    operations = [
    ]
