# Generated by Django 6.0.1 on 2026-01-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_user_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
