# Generated by Django 6.0.1 on 2026-01-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_date_completed_task_delete_this'),
        ('tasks', '0010_alter_task_user_completed'),
    ]

    operations = [
    ]
